sudo: false
before_script:
  - npm install bower
  - bower install
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 4
  - node_modules/.bin/atma server &
  - sleep 4
  - firefox http://localhost:5777/utest/ &
  - sleep 6
 
script:
  - "npm test"
 
language: node_js
node_js:
  - "5.6.0"
compiler: clang-3.4
env:
  - CXX=clang-3.4
