sudo: false

addons:
  firefox: "43.0"
  
before_script:
  - npm install bower
  - bower install
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 4
  - echo "Extracting firefox and setting PATH variable..."
  - tar -xjf /tmp/firefox-43.0.tar.bz2 --directory /tmp
  - export PATH="/tmp/firefox:$PATH"
  - echo "Using firefox version `firefox --version`"  
  - node_modules/.bin/atma server &
  - sleep 4
  - firefox http://localhost:5777/utest/ &
  - sleep 6
 
script:
  - "npm test"
 
language: node_js